.PHONY: clean All

All:
	@echo "----------Building project:[ kurs - Debug ]----------"
	@cd "kurs" && "$(MAKE)" -f  "kurs.mk"
clean:
	@echo "----------Cleaning project:[ kurs - Debug ]----------"
	@cd "kurs" && "$(MAKE)" -f  "kurs.mk" clean
